"""Collect every ranked beatmapset and the mapper behind each difficulty.

One pass over `beatmapsets/search?s=ranked` gets all four game modes at once:
without an `m` filter the endpoint returns every difficulty of each set, each
with its own `user_id`. That per-difficulty `user_id` is the only reliable way
to find guest mappers. The `Creator` line inside the .osu file is the set host,
not the difficulty's mapper, so it cannot be used for this.

The store is append-only. Rerunning with the same file only fetches what was
ranked since last time, and stops as soon as it reaches a set it already has.

    python scripts/fetch_beatsets.py                    # incremental update
    python scripts/fetch_beatsets.py --full             # ignore the store, start over
    python scripts/fetch_beatsets.py --limit 5          # first 5 pages only, for testing
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import osu_api

MODE_NAMES = ["osu", "taiko", "fruits", "mania"]

PAGE_SIZE = 50
DEFAULT_OUT = Path("data/beatsets.json")

# Printed so a long run shows progress in CI logs without flooding them.
PROGRESS_EVERY = 20


def parse_beatmapset(beatmapset: dict) -> list:
    """Reduce an API beatmapset to [host_user_id, [[beatmap_id, user_id, mode], ...]].

    Everything else the API returns is thrown away here. It would only bloat the
    store, and the graph needs nothing but who mapped what.
    """
    diffs = []
    for beatmap in beatmapset.get("beatmaps") or []:
        # Converts are generated by the game, not mapped by anyone, so they must
        # never become a collaboration edge.
        if beatmap.get("convert"):
            continue
        diffs.append([beatmap["id"], beatmap["user_id"], beatmap.get("mode_int")])

    return [beatmapset["user_id"], diffs]


def load_store(path: Path) -> dict:
    if not path.is_file():
        return {"generated": None, "sets": {}}
    with path.open(encoding="utf-8") as handle:
        store = json.load(handle)
    store.setdefault("sets", {})
    return store


def save_store(path: Path, store: dict) -> None:
    """Write via a temp file so an interrupted run cannot truncate the store."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8") as handle:
        json.dump(store, handle, separators=(",", ":"), sort_keys=False)
    tmp.replace(path)


def collect(
    token: str,
    known: set[str],
    full: bool,
    limit: int | None,
    request_delay: float = 0.5,
) -> tuple[dict, dict]:
    """Page through the search until we run out or reach a set we already have.

    Returns (newly collected sets, stats).
    """
    collected: dict[str, list] = {}
    cursor = None
    page = 0
    stopped_because = "cursor exhausted"

    while True:
        if limit is not None and page >= limit:
            stopped_because = f"hit --limit {limit}"
            break

        params = {"s": "ranked"}
        if cursor:
            params["cursor_string"] = cursor

        payload, headers = osu_api.api_get("beatmapsets/search", token, params=params)

        beatmapsets = payload.get("beatmapsets") or []
        if not beatmapsets:
            stopped_because = "empty page"
            break

        hit_known = False
        for beatmapset in beatmapsets:
            set_id = str(beatmapset["id"])
            if not full and set_id in known:
                # Results are ordered by approved_date descending, so the first
                # set we recognise means everything after it is already stored.
                hit_known = True
                break
            collected[set_id] = parse_beatmapset(beatmapset)

        page += 1
        if page % PROGRESS_EVERY == 0:
            print(f"   page {page:>4}  new sets so far {len(collected)}", flush=True)

        if hit_known:
            stopped_because = "reached a set already in the store"
            break

        cursor = payload.get("cursor_string")
        if not cursor:
            break

        # The API does not always send rate-limit headers, so the fixed delay is
        # the real guard; the header only makes us slow down further when we are
        # getting close. A full collection is around 1200 pages, which at this
        # pace takes roughly ten minutes.
        delay = max(request_delay, osu_api.throttle_delay(headers))
        if delay:
            time.sleep(delay)

    return collected, {"pages": page, "stopped_because": stopped_because}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--full", action="store_true", help="ignore the existing store")
    parser.add_argument("--limit", type=int, help="stop after this many pages (for testing)")
    parser.add_argument(
        "--delay",
        type=float,
        default=0.5,
        help="seconds to wait between pages (default: %(default)s)",
    )
    args = parser.parse_args()

    existing = {"generated": None, "sets": {}} if args.full else load_store(args.out)
    known = set(existing["sets"])
    print(f"store: {args.out}  ({len(known)} sets already collected)")

    print("requesting a token...")
    token = osu_api.get_token()

    started = time.monotonic()
    print("collecting...")
    collected, stats = collect(token, known, args.full, args.limit, args.delay)
    elapsed = time.monotonic() - started

    if collected:
        existing["sets"].update(collected)
        existing["generated"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        save_store(args.out, existing)

    total = len(existing["sets"])
    size_mb = args.out.stat().st_size / 1e6 if args.out.is_file() else 0
    print(
        f"\n{len(collected)} new sets in {stats['pages']} pages "
        f"({elapsed:.0f}s), stopped: {stats['stopped_because']}"
    )
    print(f"store now holds {total} sets, {size_mb:.1f} MB")

    if collected:
        # A quick sanity read: the same person should mostly be both the host and
        # a difficulty mapper, so a very low ratio here means something is off.
        guests = sum(
            1
            for host, diffs in collected.values()
            for _, user_id, _ in diffs
            if user_id != host
        )
        diffs_total = sum(len(diffs) for _, diffs in collected.values())
        pct = 100 * guests / diffs_total if diffs_total else 0
        print(f"guest difficulties in this batch: {guests}/{diffs_total} ({pct:.0f}%)")

    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except osu_api.CredentialsMissing as error:
        sys.stdout.flush()
        print(f"\n{error}", file=sys.stderr)
        sys.exit(2)
    except osu_api.OsuApiError as error:
        sys.stdout.flush()
        print(f"\nFAIL: {error}", file=sys.stderr)
        sys.exit(1)
